### ISSUE TITLE
License

### ISSUE THREAD

**Issue by skogsbrus** [ErikBjare/timeslot#2]
Hey Erik, what's the license on this? :)

I've never truly learnt how licensing works but if I'm reading [this](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) right, this project needs a license in order for me to distribute it together with the nix package for activitywatch (since it's a dependency of aw-core).

**Comment by skogsbrus** [comment]
Don't know how github notifications work so pinging just in case! @ErikBjare :smiley:

**Comment by ErikBjare** [comment]
@skogsbrus Consider it MIT, I'll finalize it when I get back from holiday :)

**Comment by skogsbrus** [comment]
All right, thanks! Enjoy!

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ErikBjare/timeslot/commit/c262e79a6cf7e23b08cacf7ff7408ed5326e25e6

Thanks for the notice!
